### PR TITLE
API key authentication

### PR DESCRIPTION
**Pull request by lund5000**
A working proposal for authenticating via an `api_key` defined on a User entity and passed as a query parameter to API requests.

Additional description in Trello: https://trello.com/c/UnXpqNCc/24-api-key-authentication

### CODE REVIEW

**Review by bmcdonn2 — APPROVED** [review]
Code looks good and I was able to confirm all functionality locally using your test `api_key` 😉

**Comment by lund5000** [comment]
@bmcdonn2 I put this up branch up on the main dev site, created a user with the DJ name "Overnight Automation", and generated an API key for it in Python using [secrets.token_urlsafe](https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe). I can send that your way or you can grab it from the Datastore console so we can try this out with Nite Owl and kick the tires a bit.

**Comment by bmcdonn2** [comment]
> @bmcdonn2 I put this up branch up on the main dev site, created a user with the DJ name "Overnight Automation", and generated an API key for it in Python using [secrets.token_urlsafe](https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe). I can send that your way or you can grab it from the Datastore console so we can try this out with Nite Owl and kick the tires a bit.

Yeah I spotted that entry in the datastore the other night. I'll give it a shot tonight to confirm.

**Comment by bmcdonn2** [comment]
> @bmcdonn2 I put this up branch up on the main dev site, created a user with the DJ name "Overnight Automation", and generated an API key for it in Python using [secrets.token_urlsafe](https://docs.python.org/3/library/secrets.html#secrets.token_urlsafe). I can send that your way or you can grab it from the Datastore console so we can try this out with Nite Owl and kick the tires a bit.

@lund5000 I was able to confirm the api key works and have made the corresponding changes in the nite-owl branch here: https://github.com/chirpradio/cloud-functions/commit/9d762fbb4bdda1733b4a2f11fe0f0ff8c9cffd40. 

There is an issue though where playlist entries written by this new user using the API key appears to break the [legacy playlist tracker page](https://chirpradiodev.appspot.com/playlists/). If the page attempts to load any playlist events written by this user it'll display the error page (the one with the cat). I initially thought it might be related to some of the empty fields for the overnight automation user so I manually set the first name, last name and email but it still failed to render the page. I also tried manually adjusting the linked user in one of these problematic playlist events and was able to resolve the problem by switching it to my user.

I tried digging around https://github.com/chirpradio/chirpradio to see if I could find why this might be happening but wasn't able to pinpoint anything in particular. I'll give it another look later this week unless you have any theories.

Overall, I think this PR is probably complete but there are certain aspects to the automation user itself we need to iron out to ensure playlist events written by it don't break things.

**Comment by lund5000** [comment]
@bmcdonn2 The DJDB logs in dev didn't definitively confirm it for me, but I also suspect the issue is with the User entity and not with the authentication method. I'll merge this in and try to reproduce & diagnose separately. Thanks!

**Pull request merged**
